name: dartf
description: Superpowers for Dart. A collection of useful static extension methods.
version: 0.2.0
homepage: https://github.com/alexrintt/dartf

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.1.0
  collection: ^1.15.0
  crypto: ^3.0.0
  meta: ^1.3.0
  path: ^1.8.0
  time: ^2.0.0

dev_dependencies:
  fake_async: ^1.2.0
  test: ^1.16.4
