name: Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    container:
      image: google/dart:2.12

    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Collect coverage
        run: |
          dart pub global activate test_coverage
          dart pub global run test_coverage
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
